---
development:
  cloud_name: myshalairweb
  api_key: '852315891685927'
  api_secret: ZryRUrWBeARB2ZjxryRhwWRpuC0
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: myshalairweb
  api_key: '852315891685927'
  api_secret: ZryRUrWBeARB2ZjxryRhwWRpuC0
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: myshalairweb
  api_key: '852315891685927'
  api_secret: ZryRUrWBeARB2ZjxryRhwWRpuC0
  enhance_image_tag: true
  static_file_support: false
